name: libwebkit2gtk
version: '2.24.1'
summary: WebKitGTK is a full-featured port of the WebKit rendering engine
description: |
    WebKitGTK is a full-featured port of the WebKit rendering engine,
    suitable for projects requiring any kind of web integration, from hybrid
    HTML/CSS applications to full-fledged web browsers. It offers WebKit’s
    full functionality and is useful in a wide range of systems from desktop
    computers to embedded systems like phones, tablets, and televisions.
    WebKitGTK is made by a lively community of developers and designers,
    who hope to bring the web platform to everyone.

parts:
    webkitgtk:
        after:
            - gcc-6
        plugin: cmake
        configflags:
            - -DCMAKE_INSTALL_PREFIX=/
            - -DCMAKE_BUILD_TYPE=Release
            - -DPORT=GTK
            - -DENABLE_WEB_CRYPTO=0
            - -DUSE_OPENJPEG=0
            - -DUSE_WOFF2=0
            - -DUSE_GSTREAMER_GL=0
            - -DENABLE_MEDIA_SOURCE=0
            - -DCMAKE_C_COMPILER=gcc-6
            - -DCMAKE_CXX_COMPILER=g++-6
        source: https://www.webkitgtk.org/releases/webkitgtk-2.24.1.tar.xz
        build-packages:
            - ruby
            - libgcrypt20-dev
            - libwebp-dev
            - libxslt1-dev
            - libsecret-1-dev
            - libtasn1-6-dev
            - libenchant-dev
            - libhyphen-dev
            - libjpeg-dev
            - libsoup2.4-dev
            - libxkbcommon-dev
            - libnghttp2-14
            - libpixman-1-dev
            - libsqlite3-dev
            - libgl1-mesa-dev
            - freeglut3-dev 
            - libgirepository1.0-dev
            - libgtk-3-dev
            - libgtk2.0-dev
            - libnotify-dev
            - libgstreamer1.0-dev
            - libgstreamer-plugins-base1.0-dev
        stage-packages:
            - libc6
            - libstdc++6
            - libgl1
            - libgles2
            - geoclue-2.0
            - gperf
            - gobject-introspection
    gcc-6:
        plugin: nil
        override-build: |
            sudo apt --yes install software-properties-common

            # Install newer GCC from Toolchain test builds PPA
            sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
            sudo apt update
            sudo apt --yes install gcc-6 g++-6
